id: 4f2d4a4042e24f2889645c6a0355d278
initial_creation_type: ocr
source_metadata:
  volumes:
    e179de83353746acb949c2f2db6fa21b:
      base_file: v110.txt
      image_group_id: I1PD95956
      title: ''
      total_pages: 1182
      volume_number: 111
